# Cloudflare Worker 配置文件

name = "webapp-deploy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Worker 类型
workers_dev = true

# D1 数据库绑定
# ⚠️ 重要：请将 database_id 替换为你在 Cloudflare 创建的数据库 ID
[[d1_databases]]
binding = "DB"
database_name = "nekro-webapp-db"
database_id = "977eb2a5-9f70-4b1c-8257-d4015fbec898" # 请替换为你的 Database ID

# 环境变量
[vars]
# 数据库初始化标志（Worker 首次运行时自动初始化）
DB_INITIALIZED = "false"
